[EPMGCIPART-403] Update User Profile Data for ArtObject, Proposal, and Tender
Artograd/Artograd-API pull request #22
Opened 2024-09-07 20:07 UTC by aborozdykh

2024-09-09 07:43 UTC, Maksim-Totski requested changes

2024-09-09 07:43 UTC, Maksim-Totski commented on src/main/java/com/artograd/api/helpers/UserServiceHelper.java
> +                    .setPicture(userAttributeHelper.getUserAttributeValue(attributes, "picture"));
Please refer to ENUM value from com.artograd.api.model.enums.UserAttributeKey

2024-09-09 07:43 UTC, Maksim-Totski commented on src/main/java/com/artograd/api/helpers/UserServiceHelper.java
> +                            attributes, "custom:organization"));
same

2024-09-09 07:43 UTC, Maksim-Totski commented on src/main/resources/application.yaml
> +    mails: ${SQS_EMAILS:https://sqs.eu-central-1.amazonaws.com/124092974016/dev_emails.fifo}
let it stay in env vars

2024-09-26 19:52 UTC, aborozdykh commented on src/main/java/com/artograd/api/helpers/UserServiceHelper.java
> +                    .setPicture(userAttributeHelper.getUserAttributeValue(attributes, "picture"));
Done

2024-09-26 19:52 UTC, aborozdykh commented on src/main/java/com/artograd/api/helpers/UserServiceHelper.java
> +                            attributes, "custom:organization"));
Done.

2024-09-27 06:25 UTC, Maksim-Totski approved these changes

2024-09-30 15:57 UTC, merged